---
apiVersion: v1
kind: Secret
metadata:
  name: bancswissunique-bancswissunique-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/bancswissunique-frontend-gitops
